### PR TITLE
Resolve the issue for QGIS 2.12+

### PR DESCRIPTION
**Pull request by saberraz**
Problem with not displaying the labels

### CODE REVIEW

**Comment by anitagraser** [comment]
I really cannot reproduce the issue. I just tried both osm_spatialite_googlemaps_lines.qml and osm_spatialite_tonerlite_point.qml and labels display fine in master. I don't mind merging your PR but could you describe what you changed? Or did you just re-save in a new QGIS version?

**Comment by saberraz** [comment]
Here is an example in 2.14.3, master looks fine, could be related to
http://hub.qgis.org/issues/14441
or this:
http://hub.qgis.org/issues/14224
qgis_2 14 3
qgis_2 8 9_label_properties
qgis_2 14 3_label_properties
qgis_2 8 9

**Comment by anitagraser** [comment]
Maybe your OSM database is different from mine ... here it also looks ok in 2.14.3

screenshot 2016-05-27 15 46 38

screenshot 2016-05-27 15 48 35

**Comment by andest01** [comment]
I can confirm that labels were broken in Mac OSX, QGIS v2.14. Upgrading via Kyng Chaos 2.16 fixed this issue for me.

**Pull request closed without merging**
